### PR TITLE
Recognize BIGINTs

### PR DESCRIPTION
**Pull request by imkira**
Related to
https://github.com/mariano/node-db/pull/13

### CODE REVIEW

**Comment by imkira** [comment]
Please forget the change to package.json.

**Comment by markhughes** [comment]
This pull requests should be more than considered.

**Comment by mariano** [comment]
This looks great to me! @imkira: could you fix the fact that you are moving the submodule URL for node-db away?
I did post a comment on https://github.com/mariano/node-db/pull/13

**Comment by imkira** [comment]
Hello @mariano , thanks for your feedback. I think this is what you meant. Let me know if there is something missing.

**Pull request merged**
